/**
 * Staging for images Cursor generated server-side.
 *
 * Cursor's GenerateImage runs on its servers and hands the client finished
 * bytes. OpenCode's `write` tool takes a string and additionally BOM-splits,
 * diffs, and runs `Format.file()` on what it writes, so image bytes cannot pass
 * through it — the bytes have to be written by provider code.
 *
 * That write still must raise OpenCode's permission, and `ctx.ask` is only
 * reachable inside a plugin tool's `execute`. So the bytes wait here, keyed by
 * a single-use id, and the tool that commits them takes only that id: no path
 * and no content ever crosses the tool boundary. A tool visible in the catalog
 * therefore cannot be used to write arbitrary bytes anywhere — it can only
 * commit an image this provider already received, or do nothing.
 *
 * Approach adapted from jkalasas/opencode-antigravity-image (MIT), which
 * established writing image bytes from inside a plugin tool rather than through
 * the host's text `write`. No code was copied; the permission gate, the
 * handle-only tool surface, and the containment checks are this provider's.
 */

import { randomUUID } from "node:crypto"

export type PendingCursorImage = {
  id: string
  /** Absolute target, already remapped onto a real location under this host. */
  path: string
  /** Host project folder the target was mapped into; an allowed write root. */
  projectDir?: string
  mime: string
  data: Uint8Array
  /** OpenCode session that may commit this image. */
  sessionId?: string
  createdAt: number
}

export type StageCursorImageInput = {
  path: string
  projectDir?: string
  mime: string
  data: Uint8Array
  sessionId?: string
}

/** Cursor's own edit ceiling is 50 MB; images are far smaller in practice. */
export const MAX_STAGED_IMAGE_BYTES = 50 * 1024 * 1024
/** A staged image is committed within one tool round-trip or it is stale. */
export const STAGED_IMAGE_TTL_MS = 10 * 60_000
/** Bounds memory if a turn generates several images and none are committed. */
const MAX_PENDING = 8

const pending = new Map<string, PendingCursorImage>()

export class StagedImageTooLargeError extends Error {
  constructor(bytes: number) {
    super(`Generated image is ${bytes} bytes, above the ${MAX_STAGED_IMAGE_BYTES} byte limit`)
    this.name = "StagedImageTooLargeError"
  }
}

function prune(now: number): void {
  for (const [id, image] of pending) {
    if (now - image.createdAt > STAGED_IMAGE_TTL_MS) pending.delete(id)
  }
  // Oldest-first eviction: Map preserves insertion order and ids are only ever
  // appended, so the first entries are the oldest.
  while (pending.size >= MAX_PENDING) {
    const oldest = pending.keys().next().value
    if (oldest === undefined) break
    pending.delete(oldest)
  }
}

/** Hold generated bytes and return the handle the commit tool will be given. */
export function stageCursorImage(input: StageCursorImageInput, now = Date.now()): string {
  if (input.data.length > MAX_STAGED_IMAGE_BYTES) {
    throw new StagedImageTooLargeError(input.data.length)
  }
  prune(now)
  const id = `cursor-image-${randomUUID()}`
  pending.set(id, {
    id,
    path: input.path,
    projectDir: input.projectDir,
    mime: input.mime,
    data: input.data,
    sessionId: input.sessionId,
    createdAt: now,
  })
  return id
}

/**
 * Claim a staged image. Single use: a replayed or guessed id finds nothing, so
 * the commit tool cannot be driven twice or by a caller that never had a real
 * handle.
 */
export function takePendingCursorImage(
  id: string,
  now = Date.now(),
): PendingCursorImage | undefined {
  const image = pending.get(id)
  if (!image) return undefined
  pending.delete(id)
  if (now - image.createdAt > STAGED_IMAGE_TTL_MS) return undefined
  return image
}

/** Drop a staged image whose turn ended without committing it. */
export function discardPendingCursorImage(id: string): void {
  pending.delete(id)
}

/** Test seam. */
export function clearPendingCursorImages(): void {
  pending.clear()
}

export function pendingCursorImageCount(): number {
  return pending.size
}
