/**
 * AUTO-GENERATED by scripts/generate-cursor-pricing.ts — do not edit by hand.
 * Source: https://cursor.com/docs/models-and-pricing.md
 * Regenerate: bun run generate:pricing
 */

export const CURSOR_PRICING_SOURCE = "https://cursor.com/docs/models-and-pricing.md" as const

export const CURSOR_MODEL_COSTS = {
  "claude-fable-5": {
    "input": 10,
    "output": 50,
    "cache_read": 1,
    "cache_write": 12.5
  },
  "claude-haiku-4-5": {
    "input": 1,
    "output": 5,
    "cache_read": 0.1,
    "cache_write": 1.25
  },
  "claude-opus-4-5": {
    "input": 5,
    "output": 25,
    "cache_read": 0.5,
    "cache_write": 6.25
  },
  "claude-opus-4-6": {
    "input": 5,
    "output": 25,
    "cache_read": 0.5,
    "cache_write": 6.25
  },
  "claude-opus-4-7": {
    "input": 5,
    "output": 25,
    "cache_read": 0.5,
    "cache_write": 6.25
  },
  "claude-opus-4-8": {
    "input": 5,
    "output": 25,
    "cache_read": 0.5,
    "cache_write": 6.25
  },
  "claude-opus-5": {
    "input": 5,
    "output": 25,
    "cache_read": 0.5,
    "cache_write": 6.25
  },
  "claude-sonnet-4": {
    "input": 3,
    "output": 15,
    "cache_read": 0.3,
    "cache_write": 3.75,
    "context_over_200k": {
      "input": 6,
      "output": 22.5,
      "cache_read": 0.6,
      "cache_write": 7.5
    }
  },
  "claude-sonnet-4-5": {
    "input": 3,
    "output": 15,
    "cache_read": 0.3,
    "cache_write": 3.75
  },
  "claude-sonnet-4-6": {
    "input": 3,
    "output": 15,
    "cache_read": 0.3,
    "cache_write": 3.75
  },
  "claude-sonnet-5": {
    "input": 3,
    "output": 15,
    "cache_read": 0.3,
    "cache_write": 3.75
  },
  "gemini-2.5-flash": {
    "input": 0.3,
    "output": 2.5,
    "cache_read": 0.03
  },
  "gemini-3-flash": {
    "input": 0.5,
    "output": 3,
    "cache_read": 0.05
  },
  "gemini-3.1-pro": {
    "input": 2,
    "output": 12,
    "cache_read": 0.2
  },
  "gemini-3.5-flash": {
    "input": 1.5,
    "output": 9,
    "cache_read": 0.15
  },
  "gemini-3.6-flash": {
    "input": 1.5,
    "output": 7.5,
    "cache_read": 0.15
  },
  "glm-5.2": {
    "input": 1.4,
    "output": 4.4,
    "cache_read": 0.26
  },
  "gpt-5-mini": {
    "input": 0.25,
    "output": 2,
    "cache_read": 0.025
  },
  "gpt-5.1": {
    "input": 1.25,
    "output": 10,
    "cache_read": 0.125
  },
  "gpt-5.2": {
    "input": 1.75,
    "output": 14,
    "cache_read": 0.175
  },
  "gpt-5.3-codex": {
    "input": 1.75,
    "output": 14,
    "cache_read": 0.175
  },
  "gpt-5.4": {
    "input": 2.5,
    "output": 15,
    "cache_read": 0.25,
    "context_over_200k": {
      "input": 5,
      "output": 15,
      "cache_read": 0.5
    }
  },
  "gpt-5.4-mini": {
    "input": 0.75,
    "output": 4.5,
    "cache_read": 0.075
  },
  "gpt-5.4-nano": {
    "input": 0.2,
    "output": 1.25,
    "cache_read": 0.02
  },
  "gpt-5.5": {
    "input": 5,
    "output": 30,
    "cache_read": 0.5,
    "context_over_200k": {
      "input": 10,
      "output": 30,
      "cache_read": 1
    }
  },
  "gpt-5.6-luna": {
    "input": 0.2,
    "output": 1.2,
    "cache_read": 0.02,
    "cache_write": 0.25
  },
  "gpt-5.6-sol": {
    "input": 5,
    "output": 30,
    "cache_read": 0.5,
    "cache_write": 6.25,
    "context_over_200k": {
      "input": 10,
      "output": 30,
      "cache_read": 1,
      "cache_write": 12.5
    }
  },
  "gpt-5.6-terra": {
    "input": 2,
    "output": 12,
    "cache_read": 0.2,
    "cache_write": 2.5
  },
  "kimi-k2.7-code": {
    "input": 0.95,
    "output": 4,
    "cache_read": 0.19
  },
  "kimi-k3": {
    "input": 3,
    "output": 15,
    "cache_read": 0.3
  }
} as const
